package duke.util;

public enum Alarm {
    INVALID_COMMAND, INVALID_ID,
    BLANK_DESCRIPTION,EMPTY_TODO, EMPTY_DEADLINE, EMPTY_EVENT,
    EMPTY_INDEX,
    NO_DDL_KEYWORD, NO_EVENT_KEYWORD,
    OUT_OF_RANGE,
    EMPTY_LIST,
}
