package duke.util;

public enum Alarm {
    INVALID_COMMAND, BLANK_DESCRIPTION,EMPTY_TODO,
    EMPTY_DEADLINE, EMPTY_EVENT, EMPTY_INDEX,
    EMPTY_LIST,
    NO_DDL_KEYWORD, NO_EVENT_KEYWORD, INVALID_ID, OUT_OF_RANGE,
    SAVE_ERROR,
}
