package duke.task;

import java.util.ArrayList;

/**
 * TaskList contains an ArrayList of Tasks, as well as an int counter to track number of tasks in TaskList.
 * Tasks that are created will be stored in TaskList
 */
public class TaskList {
    public ArrayList<Task> TaskList;
    public int taskIndex;

    /**
     * Creates an empty TaskList if no input is given
     */
    public TaskList() {
        this.TaskList = new ArrayList<>();
        this.taskIndex = 0;
    }

    /**
     * Copies all tasks from arrayList into TaskList
     * @param arrayList An ArrayList of Task, generated by reading the file data
     */
    public TaskList(ArrayList<Task> arrayList) {
        this.TaskList = new ArrayList<>();
        for (Task t: arrayList) {
            add(t);
        }
        System.out.println("Num of existing tasks = " + this.taskIndex + "\n");
    }

    /**
     * Adds a task to TaskList
     * @param t Task to be added
     */
    public void add(Task t) {
        this.TaskList.add(t);
        this.taskIndex++;
    }

    /**
     * Retrieves the task at given index
     * @param i Index for the Task to be retrieved in TaskList
     * @return Task stored at index of TaskList
     */
    public Task get(int i) {
        return this.TaskList.get(i);
    }

    /**
     * Removes task at given index
     * @param i Index for the Task to be removed from TaskList
     */
    public void remove(int i) {
        this.TaskList.remove(i);
        this.taskIndex--;
    }

}
